In [ ]:
"""
sklearn library breast cancer library
malignant
benign

apply the learnings
take the dataset do the preprocessing
1decision tree
2 logistic  regression
accuracy recall precisiion f1 score give the conclusion
"""

In [41]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler




from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [42]:
data = load_breast_cancer()

print("Dataset loaded successfully!")
print("Number of samples:", data.data.shape[0])
print("Number of features:", data.data.shape[1])
print("Target names:", data.target_names)

Dataset loaded successfully!
Number of samples: 569
Number of features: 30
Target names: ['malignant' 'benign']

In [43]:
X = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = pd.Series(
    data.target,
    name="target"
)

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (569, 30)
y shape: (569,)

In [44]:
X.head(10)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678
5,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,0.07613,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440
6,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,0.1794,0.05742,...,22.88,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368
7,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,0.07451,...,17.06,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510
8,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,0.2350,0.07389,...,15.49,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720
9,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,0.2030,0.08243,...,15.09,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750

In [45]:
y.head(30)
"""
here 0 is maligant
and 1 is benign"""

'\nhere 0 is maligant\nand 1 is benign'

In [46]:
print("Total missing values:", X.isnull().sum().sum())

Total missing values: 0

In [47]:
print("Duplicate rows:", X.duplicated().sum())

Duplicate rows: 0

In [48]:
print(y.value_counts())

target
1    357
0    212
Name: count, dtype: int64

In [49]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)
print("Training data:", y_train.shape)
print("Testing data:", y_test.shape)

Training data: (455, 30)
Testing data: (114, 30)
Training data: (455,)
Testing data: (114,)

In [50]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling completed!")

Scaling completed!

now creating the desicion tree

In [51]:
decision_tree = DecisionTreeClassifier(
    random_state=42
)

print("Decision Tree created!")

Decision Tree created!

In [52]:
decision_tree.fit(X_train, y_train)

print("Decision Tree trained!")

Decision Tree trained!

In [53]:
y_pred_dt = decision_tree.predict(X_test)

print("Predictions made!")
print(y_pred_dt[:20])

Predictions made!
[0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1]

In [54]:
print("Decision Tree Results")
print("---------------------")

print("Accuracy :", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall   :", recall_score(y_test, y_pred_dt))
print("F1 Score :", f1_score(y_test, y_pred_dt))

Decision Tree Results
---------------------
Accuracy : 0.9122807017543859
Precision: 0.9558823529411765
Recall   : 0.9027777777777778
F1 Score : 0.9285714285714286

creating logistic regression

In [55]:
logistic_model = LogisticRegression(
    max_iter=10000,
    random_state=42
)

print("Logistic Regression created!")

Logistic Regression created!

In [56]:

logistic_model.fit(X_train_scaled, y_train)

print("Logistic Regression trained!")

Logistic Regression trained!

In [57]:
y_pred_lr = logistic_model.predict(X_test_scaled)

print("Predictions made!")
print(y_pred_lr[:20])

Predictions made!
[0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1]

In [58]:
print("Logistic Regression Results")
print("---------------------------")

print("Accuracy :", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall   :", recall_score(y_test, y_pred_lr))
print("F1 Score :", f1_score(y_test, y_pred_lr))

Logistic Regression Results
---------------------------
Accuracy : 0.9824561403508771
Precision: 0.9861111111111112
Recall   : 0.9861111111111112
F1 Score : 0.9861111111111112

comparing both the models

In [59]:
results = pd.DataFrame({
    "Model": [
        "Decision Tree",
        "Logistic Regression"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_lr)
    ],
    "Precision": [
        precision_score(y_test, y_pred_dt),
        precision_score(y_test, y_pred_lr)
    ],
    "Recall": [
        recall_score(y_test, y_pred_dt),
        recall_score(y_test, y_pred_lr)
    ],
    "F1 Score": [
        f1_score(y_test, y_pred_dt),
        f1_score(y_test, y_pred_lr)
    ]
})

results
results.round(4)

                 Model  Accuracy  Precision  Recall  F1 Score
0        Decision Tree    0.9123     0.9559  0.9028    0.9286
1  Logistic Regression    0.9825     0.9861  0.9861    0.9861

In [60]:
print("Decision Tree")
print(classification_report(
    y_test,
    y_pred_dt,
    target_names=["Malignant", "Benign"]
))

Decision Tree
              precision    recall  f1-score   support

   Malignant       0.85      0.93      0.89        42
      Benign       0.96      0.90      0.93        72

    accuracy                           0.91       114
   macro avg       0.90      0.92      0.91       114
weighted avg       0.92      0.91      0.91       114

In [61]:
print("Logistic Regression")
print(classification_report(
    y_test,
    y_pred_lr,
    target_names=["Malignant", "Benign"]
))

Logistic Regression
              precision    recall  f1-score   support

   Malignant       0.98      0.98      0.98        42
      Benign       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

In [62]:
print("Decision Tree Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

print("Logistic Regression Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

Decision Tree Confusion Matrix:
[[39  3]
 [ 7 65]]
Logistic Regression Confusion Matrix:
[[41  1]
 [ 1 71]]